#!/usr/bin/env python3
"""Generate the Unicode M-category (Mn/Mc/Me) range table in crates/pretokie/src/util.rs.

Usage: python3 scripts/gen_unicode_marks.py
Rewrites the MARK_RANGES table in place between the GENERATED markers.
The Unicode version comes from Python's unicodedata module and is recorded
in the generated comment.
"""

import re
import sys
import unicodedata
from pathlib import Path

UTIL_RS = Path(__file__).resolve().parent.parent / "crates/pretokie/src/util.rs"


def mark_ranges():
    ranges = []
    for cp in range(0x110000):
        if 0xD800 <= cp <= 0xDFFF:
            continue
        if unicodedata.category(chr(cp)) in ("Mn", "Mc", "Me"):
            if ranges and cp == ranges[-1][1] + 1:
                ranges[-1][1] = cp
            else:
                ranges.append([cp, cp])
    return ranges


def main():
    ranges = mark_ranges()
    lines = [
        f"// GENERATED by scripts/gen_unicode_marks.py from Unicode {unicodedata.unidata_version} — do not edit by hand.",
        f"const MARK_RANGES: [(u32, u32); {len(ranges)}] = [",
    ]
    for i in range(0, len(ranges), 6):
        chunk = ", ".join(f"(0x{lo:04X}, 0x{hi:04X})" for lo, hi in ranges[i : i + 6])
        lines.append(f"    {chunk},")
    lines.append("];")
    generated = "\n".join(lines)

    src = UTIL_RS.read_text()
    new_src, n = re.subn(
        r"// GENERATED by scripts/gen_unicode_marks\.py.*?\n\];",
        generated,
        src,
        flags=re.S,
    )
    if n != 1:
        sys.exit(f"expected exactly one GENERATED block in {UTIL_RS}, found {n}")
    UTIL_RS.write_text(new_src)
    print(f"wrote {len(ranges)} ranges (Unicode {unicodedata.unidata_version}) to {UTIL_RS}")


if __name__ == "__main__":
    main()
